
services:

  front-end:
    build:
      context: ./front-end
      dockerfile: ./front-end.dockerfile
    restart: always
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"

  broker:
    build:
      context: ./broker
      dockerfile: ./broker.dockerfile
    restart: always
    ports:
      - "${BROKER_PORT}:${BROKER_PORT}"
    deploy:
      mode: replicated
      replicas: 1
