services:

  front-end:
    build:
      context: ./front-end
      dockerfile: ./front-end.dockerfile
    restart: always
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    deploy:
      mode: replicated
      replicas: 1
